### ISSUE TITLE
The basic example redirects to http://127.0.0.1:4440/

### ISSUE THREAD

**Issue by fungiboletus** [rundeck/docker-zoo#4]
Hei,

The basic example does redirect quite a few times to http://127.0.0.1:4440. Which is fine, unless you test it on a random local virtualbox VM or on a random cloud VM.

I believe adding the `RUNDECK_GRAILS_URL`  setting would not make the example much more complex.

**Comment by silviuvulcan** [comment]
I added RUNDECK_GRAILS_URL to .env before doing docker-compose up but it still redirects to 127.0.0.1

**Comment by rafaiovlabs** [comment]
Also it seems that from the code these images are built with localhost burned, from a docker-lib addition, any idea how to overwrite this sets ? .

**Comment by kevinadhiguna** [comment]
I ran to this issue when using  docker-compose.yml [here](https://github.com/rundeck/docker-zoo/blob/master/mysql/docker-compose.yml).

To solve the problem, I added `RUNDECK_GRAILS_URL: ${RUNDECK_GRAILS_URL:-localhost:4440}` in environment section of docker-compose.yml. This worked but I wanted to add environment variable to handle the URL, so it looked like this :  
`RUNDECK_GRAILS_URL: ${RUNDECK_GRAILS_URL:-localhost:4440}`

The whole `docker-compose.yml` is : 

```yml
version: '3'

services:
    rundeck:
        image: rundeck/rundeck:SNAPSHOT
        # links:
        #   - mysql
        depends_on:
          - mysql
        environment:
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: ${RUNDECK_DATABASE_USERNAME:-rundeck}
            RUNDECK_DATABASE_PASSWORD: ${RUNDECK_DATABASE_PASSWORD:-rundeck}
            RUNDECK_DATABASE_URL: ${RUNDECK_DATABASE_URL:-jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false}
            # Add 'RUNDECK_GRAILS_URL' to avoid host changing to localhost (see more : https://github.com/rundeck/rundeck/issues/671)
            # 'RUNDECK_GRAILS_URL' can be remote IP address, such as 43.133.23.165 or hostname, like https://mywebsite.com
            RUNDECK_GRAILS_URL: ${RUNDECK_GRAILS_URL:-localhost:4440}
        # volumes:
        #   - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
        ports:
          - 4440:4440
    mysql:
        image: mysql:5.7
        # expose:
        #   - 3306
        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
          MYSQL_DATABASE: ${MYSQL_DATABASE:-rundeck}
          MYSQL_USER: ${MYSQL_USER:-rundeck}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD:-rundeck}
        volumes:
          - dbdata:/var/lib/mysql

volumes:
    dbdata:
```


Also, this is the `.env` file that includes environment variables and thier values : 

```env
RUNDECK_DATABASE_USERNAME=rundeck
RUNDECK_DATABASE_PASSWORD=rundeck
RUNDECK_DATABASE_URL=jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
RUNDECK_GRAILS_URL=https://mywebsite.com
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=rundeck
MYSQL_USER=rundeck
MYSQL_PASSWORD=rundeck
```

Feel free to change the value of `RUNDECK_GRAILS_URL` in `.env`.

You can have a look here to check them all, including how to run the docker-compose and its setup : 
- [Rundeck - MySQL](https://github.com/kevinadhiguna/jiyu/tree/master/rundeck/rundeck-mysql)
- [Rundeck - H2 (embedded database)](https://github.com/kevinadhiguna/jiyu/tree/master/rundeck/rundeck-h2)
